# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 621e8fe5f3b5f7799f056b84c5a0138006f62e9737fa696ac02e1b577b728eceae93d37c2f16d506e73f7b657112f54d725a2e99dc6c3cc469f6eab4539a6659
  B2C_client_id: <%= ENV["B2C_CLIENT_ID"] %>
  B2C_client_secret: <%= ENV["B2C_SECRET"] %>
  BC2_Assertion_secret: <%= ENV["B2C_ASSERTION_KEY"] %>
  B2C_api_client_id: <%= ENV["B2C_API_CLIENT_ID"] %>
  B2C_api_client_secret: <%= ENV["B2C_API_CLIENT_SECRET"] %>
  B2C_api_resource: <%= ENV["B2C_API_RESOURCE"] %>
  B2C_api_basic: <%= ENV["B2C_API_BASIC"] %>

test:
  secret_key_base: 38d2c493510aa6b438b0c7d13c7d2978c0eed06586c5ac0d6d5ea3c285ddbb2af53cc4323d4e664ea6af285ac52d68c09bafd4262e7679f832137e72e3b5493d
  B2C_client_id: <%= ENV["B2C_CLIENT_ID"] %>
  B2C_client_secret: <%= ENV["B2C_SECRET"] %>
  BC2_Assertion_secret: <%= ENV["B2C_ASSERTION_KEY"] %>
  B2C_api_client_id: <%= ENV["B2C_API_CLIENT_ID"] %>
  B2C_api_client_secret: <%= ENV["B2C_API_CLIENT_SECRET"] %>
  B2C_api_resource: <%= ENV["B2C_API_RESOURCE"] %>
  B2C_api_basic: <%= ENV["B2C_API_BASIC"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  B2C_client_id: <%= ENV["B2C_CLIENT_ID"] %>
  B2C_client_secret: <%= ENV["B2C_SECRET"] %>
  BC2_Assertion_secret: <%= ENV["B2C_ASSERTION_KEY"] %>
  B2C_api_client_id: <%= ENV["B2C_API_CLIENT_ID"] %>
  B2C_api_client_secret: <%= ENV["B2C_API_CLIENT_SECRET"] %>
  B2C_api_resource: <%= ENV["B2C_API_RESOURCE"] %>
  B2C_api_basic: <%= ENV["B2C_API_BASIC"] %>
  
